services:
  loganne:
    build: .
    container_name: lucos_loganne
    ports: 
      - $PORT:$PORT
      - "8119:8119"
    environment:
      - PORT
      - CLIENT_KEYS
      - WEBSOCKET_PORT=8119
      - STATE_DIR=/var/lib/loganne
      - SYSTEM
      - KEY_LUCOS_MEDIA_MANAGER
      - KEY_LUCOS_MEDIA_WEIGHTINGS
      - KEY_LUCOS_ARACHNE
      - KEY_LUCOS_PHOTOS
      - KEY_LUCOS_MONITORING
    image: lucas42/lucos_loganne:${VERSION:-latest}
    volumes:
      - state:/var/lib/loganne
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  state: